### ISSUE TITLE
move binary release move 1.8.0-rc.1 work error 

### ISSUE THREAD

**Issue by stone99** [starcoinorg/starcoin#3064] opened 2021-12-01 02:48 UTC
# move unit-test src/modules/Mymodule.move
1. download file from release page: https://github.com/starcoinorg/starcoin/releases/download/v1.8.0-rc.1/move-macos-latest
2. mv move-macos-latest to ~/.cargo/bin/move
3. execute `move unit-test src/modules/Mymodule.move`
get error: 
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: No such file or directory '/Users/runner/.cargo/git/checkouts/diem-5aa6d6b8b0487904/6ff224f/language/move-stdlib/nursery/UnitTest.move'', /Users/runner/.cargo/git/checkouts/diem-5aa6d6b8b0487904/6ff224f/language/tools/move-unit-test/src/lib.rs:106:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
the runner is not a user on my computer, it may be the user in the ci executing pipeline as  @jolestar said.
it seems that the release file was not compiled correctly.

**Comment by jolestar** [comment] 2021-12-01 03:03
please provide the src/modules/Mymodule.move

**Comment by stone99** [comment] 2021-12-01 03:17
it is not a special file, I just copy it from the official tutorial demo:
```
address 0x2{
module MyModule {

    struct MyCoin has key { value: u64 }

    public fun make_sure_non_zero_coin(coin: MyCoin): MyCoin {
        assert(coin.value > 0, 0);
        coin
    }

    public fun has_coin(addr: address): bool {
        exists<MyCoin>(addr)
    }
    
    #[test]
    fun make_sure_non_zero_coin_passes() {
        let coin = MyCoin { value: 1 };
        let MyCoin { value: _ } = make_sure_non_zero_coin(coin);
    }
    #[test]
    // Or #[expected_failure] if we don't care about the abort code
    #[expected_failure(abort_code = 0)]
    fun make_sure_zero_coin_fails() {
        let coin = MyCoin { value: 0 };
        let MyCoin { value: _ } = make_sure_non_zero_coin(coin);
    }
    #[test_only] // test only helper function
    fun publish_coin(account: &signer) {
        move_to(account, MyCoin { value: 1 })
    }
    #[test(a = @0x1, b = @0x2)]
    fun test_has_coin(a: signer, b: signer) {
        publish_coin(&a);
        publish_coin(&b);
        assert(has_coin(@0x1), 0);
        assert(has_coin(@0x2), 1);
        assert(!has_coin(@0x3), 1);
    }
}
}
```

**Comment by stone99** [comment] 2021-12-01 03:51
By the way, here is a word lost in the tutorial of function test phrase: 
https://starcoin.org/zh/developer/blog/move_development/ 
```
1.功能测试的组成
功能测试可以分为个板块：

全局配置
新区块的生成
区块的交易
执行的交易代码
```
I think it should be:
```
1.功能测试的组成
功能测试可以分为(x)个板块：

全局配置
新区块的生成
区块的交易
执行的交易代码
```

**Comment by lerencao** [comment] 2021-12-02 01:25
Interesting. I cannot reproduce the bug.

**Comment by lerencao** [comment] 2021-12-02 05:00
Thanks for the reports.
I have created #3066 to fix this.
After this is merged, you can build `move` binary from master branch using cargo command: `cargo build --release --bin move`, then use the move binary at `./target/release/move`.

**Closed** 2021-12-02 07:41 UTC
Labels: bug, area:move-cli
